version: "2"

linters:
  default: standard
  enable:
    - errorlint
    - gocritic
    - misspell
    - revive
    - unconvert
    - usestdlibvars
  settings:
    revive:
      rules:
        - name: exported
        - name: error-strings
        - name: context-as-argument
        - name: indent-error-flow
  exclusions:
    paths:
      - gen
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - gen
